### ISSUE TITLE
Jira connector availability

### ISSUE THREAD

**Issue by cicoub13** [optittm/bugprediction#19]
Hello.

After BDX I/O presentation, I'm trying to test the project but I don't understand how to configure JIRA connector to fetch issues from my project.

Is it available ?

**Comment by bbalet** [comment]
Hi,

We're working on it. Please wait a bit it should be merged in two weeks.

**Comment by aurelien-alet** [comment]
Hello,

The feature has been merged. News configurations are available in .env file, allowing you to: 
- **OTTM_JIRA_BASE_URL**: specify the url of your jira instance
- **OTTM_JIRA_PROJECT **: specify the project identifier
- **OTTM_JIRA_EMAIL**, **OTTM_JIRA_TOKEN**: specify your credentials (email AND token are required)
- **OTTM_JIRA_ISSUE_TYPE**: specify the jira issueType if needed

You also have to tell to the tool that the used source bug is Jira (OTTM_SOURCE_BUGS=jira).

The optionnal label selector for bugs (**OTTM_ISSUE_TAGS**) is also available for Jira.

If it's OK for you I will close this issue.

**Comment by cicoub13** [comment]
Good for me, thanks 🙏 you can close the issue
